name: buildbase
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  flutter_svg: ^2.0.4
  dio: ^5.0.3
  intl: ^0.17.0
  flutter_form_builder: ^7.8.0
  get_it: ^7.2.0
  file_picker: ^5.2.6
  connectivity_plus: ^3.0.3
  dartz: ^0.10.1
  unicons: ^2.1.1
  animate_do: ^3.0.2
  path_provider: ^2.0.14
  sembast: ^3.4.3
  colorize: ^3.0.0
  change_app_package_name: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  responsive_ui: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay-Regular.ttf
        - asset: fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: fonts/RedHatDisplay-Black.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
